### PR TITLE
Added aliases and annotations support, reorganized tables for better tailoring to each graph

### PR DESCRIPTION
**Pull request by monprin**
Now with 1 less bug!

### CODE REVIEW

**Comment by schae234** [comment]
Can we remove the included annotation file and put a small example or stub as the one that is included in the repo? I don't want to run into bloating repo cloning with tons of included data files like what happened with Camoco before. 

You might have run into a weird situations where you are not able to actually remove the file from the repo ... This happened to me with Camoco and after including some default files it was taking like 10 mins to do a clone. You might need to do some under the hood work to actually remove all traces of the text file from the repo.

**Comment by monprin** [comment]
That makes a certain amount of sense, but to be fair, this table is only 4.1 MB, Are we going to be adding a lot more? Or could we just keep it at this one as the example?

**Comment by schae234** [comment]
Absolutely fair points. I'm just saying that I said the same thing and then suddenly it was taking 10 mins to clone a repo. My biggest concern are things like Travis where they cap you at an hour. If we were to add tests or something in the future, why waste 10% of your time on the clone?

Also, we went through the trouble of making it general (any gene to any annotation) so why include something that is maize specific?

**Comment by monprin** [comment]
Okay I will plan on taking it out, and coming up with som sort of stub in conjunction with notes in the eventual docs. 

Also just for your information going forward, at the moment, i believe this site is maize specific (I found a number of hardcoded things that I have fixed, but I am fairly sure there are more somewhere), the problem is that since we don't have another working species, I can't find those other issues, which if meesh's data is good, I'd like to use that for getting a second species up and running.

**Comment by monprin** [comment]
Need to remove the file.

**Pull request closed without merging**
